[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yhames", email = "wjddn494@naver.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "sqlmodel>=0.0.39",
    "uvicorn>=0.52.3",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
